// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using buoi5.Models;

#nullable disable

namespace buoi5.Migrations
{
    [DbContext(typeof(BookDbContext))]
    [Migration("20250526074043_SeedBookData")]
    partial class SeedBookData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("buoi5.Models.Book", b =>
                {
                    b.Property<string>("BookId")
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("Author")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BookId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = "B00001",
                            Author = "Nguyễn Văn A",
                            CategoryId = 1,
                            Image = "csharpcanban.jpg",
                            Price = 85000m,
                            Title = "C# căn bản cho người mới bắt đầu"
                        },
                        new
                        {
                            BookId = "B00002",
                            Author = "Trần Thị B",
                            CategoryId = 1,
                            Image = "aspnetcoremvc.jpg",
                            Price = 110000m,
                            Title = "ASP.NET Core MVC thực chiến"
                        },
                        new
                        {
                            BookId = "B00003",
                            Author = "Robert Kiyosaki",
                            CategoryId = 2,
                            Image = "dayconlamgiau.jpg",
                            Price = 99000m,
                            Title = "Dạy con làm giàu"
                        },
                        new
                        {
                            BookId = "B00004",
                            Author = "Nguyễn Nhật Ánh",
                            CategoryId = 3,
                            Image = "tohoclaptrinh.jpg",
                            Price = 75000m,
                            Title = "Tớ học lập trình"
                        },
                        new
                        {
                            BookId = "B00005",
                            Author = "Gary Chapman",
                            CategoryId = 4,
                            Image = "5ngonngutinhyeu.jpg",
                            Price = 105000m,
                            Title = "5 ngôn ngữ tình yêu"
                        },
                        new
                        {
                            BookId = "B00006",
                            Author = "Stephen Hawking",
                            CategoryId = 5,
                            Image = "vutrutrongvo.jpg",
                            Price = 120000m,
                            Title = "Vũ trụ trong vỏ hạt dẻ"
                        });
                });

            modelBuilder.Entity("buoi5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Lập trình"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Kỹ năng sống"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Thiếu nhi"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Tâm lý - Giáo dục"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Khoa học phổ thông"
                        });
                });

            modelBuilder.Entity("buoi5.Models.Book", b =>
                {
                    b.HasOne("buoi5.Models.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("buoi5.Models.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
